title: "Madiha Bencekri's Portfolio"
description: "A polished portfolio showcasing my expertise in Transportation Engineering, Smart Cities, and Urban Planning."
baseurl: "" # Leave empty for root
url: "https://dihaben.github.io/Madiha-Bencekri"
author: "Madiha Bencekri"
