# Site Metadata
title: "Madiha Bencekri's Portfolio"
description: "A professional portfolio showcasing my work, publications, and achievements."
author: "Madiha Bencekri"
baseurl: "" # Leave empty for GitHub Pages at the root
url: "https://dihaben.github.io/Madiha-Bencekri/" # Replace <your-github-username> with your GitHub username
lang: "en" # Set default language (can be useful for SEO)

# Navigation Menu
menu:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about.html"
  - title: "Education"
    url: "/education.html"
  - title: "Experience"
    url: "/experience.html"
  - title: "Publications"
    url: "/publications.html"
  - title: "Awards"
    url: "/awards.html"
  - title: "Languages"
    url: "/languages.html"
  - title: "Teaching"
    url: "/teaching.html"
  - title: "Projects"
    url: "/projects.html"
  - title: "Resume"
    url: "/resume.html"
  - title: "Contact"
    url: "/contact.html"
  - title: "Blog"
    url: "/blog.html"

# Plugins
plugins:
  - jekyll-seo-tag # Adds metadata for search engine optimization
  - jekyll-sitemap # Generates a sitemap.xml for SEO
  - jekyll-feed # Adds an RSS feed for your site (optional for blogs)
  - jekyll-paginate # Enables pagination for blog posts
  - jekyll-assets # Simplifies asset management (optional but useful)

# Exclude Files and Directories
exclude:
  - README.md
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock

# Pagination Settings (Optional)
paginate: 5 # Number of posts per page for blogs
paginate_path: "/blog/page:num/"

# Defaults (Optional Enhancements)
defaults:
  - scope:
      path: "" # Applies to all files
      type: "posts"
    values:
      layout: "post" # Default layout for blog posts
      author: "Madiha Bencekri"

# Social Media Links (Optional for Footer or Sidebar)
social_links:
  - name: "GitHub"
    url: "https://github.com/<your-github-username>"
  - name: "LinkedIn"
    url: "https://linkedin.com/in/<your-linkedin-username>"
  - name: "Twitter"
    url: "https://twitter.com/<your-twitter-handle>"

# SEO Settings
seo:
  title: "Madiha Bencekri | Portfolio"
  description: "Showcasing work, publications, and achievements."
  keywords: "Portfolio, Madiha Bencekri, Publications, Resume, Projects"
  image: "/assets/images/profile.jpg" # Path to your profile image

# Markdown Configuration
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown
