title: "Madiha Bencekri's Portfolio"
description: "A professional portfolio showcasing my work, publications, and achievements."
baseurl: "" # Leave empty for root
url: "https://dihaben.github.io/Madiha-Bencekri"
author: "Madiha Bencekri"
